// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwH0AbIoTecy1f92Yy_YQ0iPDb-HwZgmU',
    appId: '1:523366102153:web:b66159b0cd07707ac28258',
    messagingSenderId: '523366102153',
    projectId: 'picme-2487d',
    authDomain: 'picme-2487d.firebaseapp.com',
    storageBucket: 'picme-2487d.firebasestorage.app',
    measurementId: 'G-MCS2FMW8QG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFV-h70yhe8QYyYl2Epoo51jGq0rK_2DM',
    appId: '1:523366102153:android:973b296bd723cb01c28258',
    messagingSenderId: '523366102153',
    projectId: 'picme-2487d',
    storageBucket: 'picme-2487d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh9VOoI1jCrNeigxyl7losMqS8EXavePg',
    appId: '1:523366102153:ios:cba7c4b9fcef877ac28258',
    messagingSenderId: '523366102153',
    projectId: 'picme-2487d',
    storageBucket: 'picme-2487d.firebasestorage.app',
    iosBundleId: 'com.picme.app.picme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh9VOoI1jCrNeigxyl7losMqS8EXavePg',
    appId: '1:523366102153:ios:cba7c4b9fcef877ac28258',
    messagingSenderId: '523366102153',
    projectId: 'picme-2487d',
    storageBucket: 'picme-2487d.firebasestorage.app',
    iosBundleId: 'com.picme.app.picme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwH0AbIoTecy1f92Yy_YQ0iPDb-HwZgmU',
    appId: '1:523366102153:web:e0c273229939068ac28258',
    messagingSenderId: '523366102153',
    projectId: 'picme-2487d',
    authDomain: 'picme-2487d.firebaseapp.com',
    storageBucket: 'picme-2487d.firebasestorage.app',
    measurementId: 'G-MRD4VPM4JW',
  );
}
